User.create(name: "admin", username: "admin", password: "admin")
Ingredient.create(name: "Tomato")
Ingredient.create(name: "Onion")
Ingredient.create(name: "Garlic")
Ingredient.create(name: "Milk")
Ingredient.create(name: "Chicken")
Ingredient.create(name: "Beef")
Ingredient.create(name: "Sugar")
Ingredient.create(name: "Olive Oil")